#!/usr/bin/env bash
#Bash script that displays To infinity and beyond indefinitely,
With sleep 2 iteration d Iam invincible sigterm signal 
trap 'echo "I am invincible!!!"' SIGTERM 
while true
do
echo "To infinity and beyond"
sleep 2
done
